import { mkdir, access, writeFile } from 'node:fs/promises';
import path from 'node:path';

const exists = async target => {
  try {
    await access(target);
    return true;
  } catch {
    return false;
  }
};

export async function createApp(appName) {
  const appPath = path.resolve(appName);
  const directoryName = path.basename(appPath);
  if (!/^[a-zA-Z0-9._-]+$/.test(directoryName)) {
    throw new Error('Application name may contain only letters, numbers, dots, hyphens, and underscores.');
  }
  if (await exists(appPath)) throw new Error(`Directory "${appName}" already exists`);

  await mkdir(path.join(appPath, 'src'), { recursive: true });
  const packageJson = {
    name: appName,
    private: true,
    version: '0.1.0',
    type: 'module',
    scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    dependencies: { 'onekit-js': '^3.1.8' },
    devDependencies: { vite: '^7.2.6', typescript: '^5.9.3' }
  };

  await writeFile(path.join(appPath, 'package.json'), JSON.stringify(packageJson, null, 2) + '\n');
  await writeFile(path.join(appPath, 'vite.config.ts'), `import { defineConfig } from 'vite';

export default defineConfig({
  server: { allowedHosts: true }
});
`);
  await writeFile(path.join(appPath, 'index.html'), `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${appName}</title></head>
<body><main id="app"></main><script type="module" src="/src/main.ts"></script></body></html>\n`);
  await writeFile(path.join(appPath, 'src', 'main.ts'), `import { effect, reactive } from 'onekit-js';
import './style.css';

const state = reactive({ count: 0 });
const app = document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML = '<section class="card"><p class="eyebrow">OneKit JS</p><h1>${appName}</h1><p id="count"></p><button id="increment">Increment</button></section>';
const count = document.querySelector<HTMLParagraphElement>('#count')!;
effect(() => { count.textContent = \`Count: \${state.count}\`; });
document.querySelector<HTMLButtonElement>('#increment')!.addEventListener('click', () => state.count++);
`);
  await writeFile(path.join(appPath, 'src', 'style.css'), `:root { font-family: system-ui, sans-serif; color: #172033; background: #eef2ff; } body { display: grid; min-height: 100vh; margin: 0; place-items: center; } .card { padding: 3rem; text-align: center; background: white; border-radius: 20px; box-shadow: 0 20px 50px rgb(0 0 0 / 10%); } button { padding: .7rem 1rem; color: white; background: #5757d5; border: 0; border-radius: 8px; cursor: pointer; } .eyebrow { color: #5757d5; font-weight: 700; text-transform: uppercase; }\n`);
  await writeFile(path.join(appPath, 'README.md'), `# ${appName}\n\n## Development\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nThis starter was generated by OneKit JS CLI.\n`);
}
